### ISSUE TITLE
NVM comparison? 

### ISSUE THREAD

**Issue by J3m5** [pd4d10/nn#1]
Hi, I was wondering, what are the benefits from using nvmx instead of NVM?

And how do you handle npm packages installed with older version of node when you install a new one?

**Comment by pd4d10** [comment]
@J3m5 The initial motivation is, I need a nvm works at Windows. nvmx is only for macOS and Linux

In addition, nvmx also support nightly, rc, v8-canary version of Node.js, and Microsoft's node-chakaracore

> And how do you handle npm packages installed with older version of node when you install a new one?

npm packages are seperated, as nvm does. We'll provide a command `migrate` to migrate all packages of one version to another, soon

**Comment by pd4d10** [comment]
Seems the name "nvmx" is already used by [this project](https://www.npmjs.com/package/nvmx)

And it may be too similar to "nvm".

Renamed to "nn" to avoid confusion.
